name: Lint, Format, Typecheck
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Set up environment
        run: cp .env.example .env
      - name: Typecheck
        run: bun typecheck
      - name: Lint
        run: bun lint
      - name: Format
        run: bun format:check
